server:
  port: 8081
  servlet:
    context-path: /springboot-project
jingzhun:
  username: yunwujie
  password: 123456
  tokenUrl: http://api.ijingzhun.com/auth/token
  oceanUrl: http://api.ijingzhun.com/trace/ocean
  declareUrl: http://api.ijingzhun.com/trace/getBlnoDeclare
#  declareUrl: http://api.ijingzhun.com/trace/getBlnoDeclare?blno={blno}&ieid={ieid}
#spring:
#  redis:
#    host: 192.168.136.133
#    password: magang

#mg:
#  demo:
#    name: 马刚
#    age: 32
#    phone: 13125169793

mg:
  demo:
    name: 马刚
    age: 32
    phone: 13125169793

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mgtest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: root

#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package:
#  mapper-locations:

# 日志打印级别
logging:
  level:
    root: DEBUG

sso:
  oauth2:
    client:
      white-list1: mg,ml,mch
      white-list2: "['mg','ml','mch']"
wx:
  applet:
    appid: 10086
test:
  username: mg
  age: 18
  #hobby: ['eat','play','sleep']#只能在@ConfigurationProperties用，在@Value要用""括起来
  hobby:
    - 'eat'
    - 'play'
    - 'sleep'
  #yml中这种json格式只能用@ConfigurationProperties修饰类来解析
  great: {"niu1":"nb1","niu2":"nb2"}
  #yml中用@Value的spEL表达式时，要用""括起来
  great4: "{'niu1':'nb1','niu2':'nb2'}"
  great3:
    niu3: "nb3"
    niu4: "nb4"